name: CI Checker

on:
  pull_request:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - id: configurepages
        uses: actions/configure-pages@v5

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        run: yarn
        
      - name: Run linter
        run: yarn lint
        
      - name: Build project
        run: yarn build
        env:
          EXPORT: 1
          UNOPTIMIZED: 1
          BASE_PATH: ${{ steps.configurepages.outputs.base_path }}
